# Site settings
name: Noah Rogers
title: Noah Rogers
description: Hello, my name is Noah. I'm web designer from Southeastern Wisconsin.
highlighter: pygments

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
    - smart

# Sass settings
sass:
  sass_dir: assets/stylesheets
