# Site settings
name: Noah Rogers
title: Noah Rogers
description: Hello, my name is Noah. I'm a freelance frontend web developer from Southeastern Wisconsin.
highlighter: pygments

# Build settings
markdown: kramdown

# Sass settings
sass:
  sass_dir: assets/stylesheets
