# Site settings
name: Noah Rogers
title: Noah Rogers
description: Hello, my name is Noah Rogers, I'm a designer at 8th Light.

# Build settings
highlighter: rouge
markdown: kramdown

# Sass settings
sass:
  sass_dir: assets/stylesheets
