# Site settings
name: Noah Rogers
title: Noah Rogers
description: "Personal blog and projects"
highlighter: pygments

# Build settings
markdown: kramdown

# Sass settings
sass:
  sass_dir: assets/stylesheets
