# Site settings
name: Noah Rogers
title: Noah Rogers
description: Hello, my name is Noah. I am a design apprentice at 8th Light.

# Build settings
highlighter: rouge
markdown: kramdown

# Sass settings
sass:
  sass_dir: assets/stylesheets
