# Site settings
name: Noah Rogers
title: Noah Rogers
description: Hello, my name is Noah. I am a design apprentice at 8th Light.
highlighter: Rouge

# Build settings
markdown: kramdown

# Sass settings
sass:
  sass_dir: assets/stylesheets
